name: Terraform Destroy

on:
    workflow_dispatch:
        inputs:
            confirm_destroy:
                description: "Type DESTROY to confirm"
                required: true

permissions:
    contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      TF_VAR_project: my-ever-first-project   # Replace with your GCP project ID
      GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }} # Service account JSON stored in GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6   # Compatible with "~> 1.0" constraint

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false